-- v2 follow-up (Item 1 of two user-approved post-final-review items; Item 2 is the group-leave
-- feature in the next migration). Closes finding I6 from the final whole-branch review.
--
-- friendship_settings' three original columns (20260815000001_v2_accountability_schema.sql:47-49)
-- - send_live_nudges, receive_live_nudges, receive_daily_digest - all default true. That directly
-- contradicts this plan's own Global Constraint (docs/V2_Implementation_Plan.md:27): "Friend-
-- visible data stays field-gated ... default to minimal visibility, enforced with Postgres Row
-- Level Security, not just client-side filtering." It's also inconsistent with Task 10's five
-- newer share_* toggles (20260815000012_v2_privacy_controls.sql:97-112), which all correctly
-- default false for exactly this reason ("most-private-by-default", per that migration's own
-- comment). A new group member today starts fully opted-IN on the nudge/digest axis and fully
-- opted-OUT on every other axis - the same person, the same trust boundary, two contradictory
-- defaults. This was flagged as a genuine plan self-contradiction (not an implementation bug) and
-- surfaced to the product owner rather than resolved unilaterally, per this project's standing
-- practice for judgment calls the plan doesn't itself resolve (see Task 10's precedent). Product
-- decision: flip these three to default false too, so every new group member starts fully
-- opted-out on every axis, symmetric with the five newer toggles.
--
-- Column-default-only change, deliberately minimal:
-- create_friendship_settings_for_new_member() (20260815000012_v2_privacy_controls.sql:67-90)
-- never specifies these three columns in either of its two `insert into friendship_settings
-- (user_id, friend_user_id) select ...` statements - it relies entirely on the table's column
-- defaults for every column it doesn't name. Confirmed by reading that function again here: no
-- change to it is needed, changing the column default is sufficient by itself to flip the trigger's
-- behavior for every future group join.
--
-- Deliberately NOT backfilled: this changes the default for newly-created rows only (new group
-- joins going forward). Existing friendship_settings rows are out of scope for this migration -
-- per this dispatch's brief, all such rows in the live project today are ephemeral test-account
-- data created by this session's own verify-*.mjs scripts, not real users, so there is nothing to
-- migrate for real accounts, and writing a broad UPDATE against existing data was explicitly
-- excluded from scope.
alter table friendship_settings alter column send_live_nudges set default false;
alter table friendship_settings alter column receive_live_nudges set default false;
alter table friendship_settings alter column receive_daily_digest set default false;
